"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def even_fibo(n):
    i=0
    nth=0
    n1,n2=0,1
    sum=0
    while i<n:
        nth=n1+n2
        n1=n2
        n2=nth
        if nth%2 ==0:
            sum+=nth
        i+=1
    return sum
    
print(even_fibo(4000000))


